### ISSUE TITLE
Does it support real time data?

### ISSUE THREAD

**Issue by Luc45** [jc21/clitable#4]
Hello,

Is it possible to render a table where the fields updates their values in real time according to what's happening in the CLI script?

For instance: `327/4272 records processed`, where `327` is incremented for each record.

Thank you.

**Comment by jc21** [comment]
No it's not possible with this script sorry

**Comment by Luc45** [comment]
Thanks. Try this:

```php
<?php

for ($i=0;$i<10;$i++) {
	echo "\rIteration $i";
	sleep(1);
}
```

Save this as `foo.php` and run `php foo.php`

PS: The secret is carriage return `\r`

Anyway, thanks for this open-source tool man.

**Comment by conrad10781** [comment]
@Luc45 , old ticket, but you could probably also use PHP's ncurses implementation so that you're not moving content down the screen causing a large scroll area.
